name: ET CI Checks

on: [push, pull_request, workflow_dispatch]

jobs:
  md_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          globs: '**/*.md'
          config_file: 'markdownlint.json'
